linters:
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unused
